Return-Path: <linux-sh-owner@vger.kernel.org>
X-Original-To: lists+linux-sh@lfdr.de
Delivered-To: lists+linux-sh@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 561521AA76
	for <lists+linux-sh@lfdr.de>; Sun, 12 May 2019 06:30:07 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1725932AbfELEaG (ORCPT <rfc822;lists+linux-sh@lfdr.de>);
        Sun, 12 May 2019 00:30:06 -0400
Received: from mail02.asahi-net.or.jp ([202.224.55.14]:41835 "EHLO
        mail02.asahi-net.or.jp" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1725919AbfELEaG (ORCPT
        <rfc822;linux-sh@vger.kernel.org>); Sun, 12 May 2019 00:30:06 -0400
Received: from h61-195-96-97.vps.ablenet.jp (h61-195-96-97.vps.ablenet.jp [61.195.96.97])
        (Authenticated sender: PQ4Y-STU)
        by mail02.asahi-net.or.jp (Postfix) with ESMTPA id DC9AB3DD6D;
        Sun, 12 May 2019 13:30:00 +0900 (JST)
Received: from yo-satoh-debian.ysato.ml (ZM005235.ppp.dion.ne.jp [222.8.5.235])
        by h61-195-96-97.vps.ablenet.jp (Postfix) with ESMTPSA id A2FFB240085;
        Sun, 12 May 2019 13:29:59 +0900 (JST)
Date:   Sun, 12 May 2019 13:29:56 +0900
Message-ID: <87tve0qoqj.wl-ysato@users.sourceforge.jp>
From:   Yoshinori Sato <ysato@users.sourceforge.jp>
To:     Nick Desaulniers <ndesaulniers@google.com>
Cc:     dalias@libc.org, geert@linux-m68k.org, luto@kernel.org,
        clang-built-linux@googlegroups.com,
        Masahiro Yamada <yamada.masahiro@socionext.com>,
        linux-sh@vger.kernel.org, linux-kernel@vger.kernel.org
Subject: Re: [PATCH v2] sh: vsyscall: drop unnecessary cc-ldoption
In-Reply-To: <20190424180223.253025-1-ndesaulniers@google.com>
References: <CAK7LNASLBQ=w9YFBD80s7dit1bd_Tr+ggVyRNms0jf1pR9k=ZA@mail.gmail.com>
        <20190424180223.253025-1-ndesaulniers@google.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM/1.14.9 (=?ISO-8859-4?Q?Goj=F2?=) APEL/10.8 EasyPG/1.0.0 Emacs/25.1
 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-sh-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-sh.vger.kernel.org>
X-Mailing-List: linux-sh@vger.kernel.org

On Thu, 25 Apr 2019 03:02:21 +0900,
Nick Desaulniers wrote:
> 
> Towards the goal of removing cc-ldoption, it seems that --hash-style=
> was added to binutils 2.17.50.0.2 in 2006. The minimal required version
> of binutils for the kernel according to
> Documentation/process/changes.rst is 2.20.
> 
> Link: https://gcc.gnu.org/ml/gcc/2007-01/msg01141.html
> Cc: clang-built-linux@googlegroups.com
> Suggested-by: Masahiro Yamada <yamada.masahiro@socionext.com>
> Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

Acked-by: Yoshinori Sato <ysato@users.sourceforge.jp>

> ---
> Changes V1 -> V2:
> * update commit subject and message as per Masahiro/Geert.
> 
> To Geert's question about minimum binutils versions; no change needed to
> binutils.
> 
> 
>  arch/sh/kernel/vsyscall/Makefile | 3 +--
>  1 file changed, 1 insertion(+), 2 deletions(-)
> 
> diff --git a/arch/sh/kernel/vsyscall/Makefile b/arch/sh/kernel/vsyscall/Makefile
> index 5db6579bc44c..6e8664448048 100644
> --- a/arch/sh/kernel/vsyscall/Makefile
> +++ b/arch/sh/kernel/vsyscall/Makefile
> @@ -15,8 +15,7 @@ quiet_cmd_syscall = SYSCALL $@
>  
>  export CPPFLAGS_vsyscall.lds += -P -C -Ush
>  
> -vsyscall-flags = -shared -s -Wl,-soname=linux-gate.so.1 \
> -		$(call cc-ldoption, -Wl$(comma)--hash-style=sysv)
> +vsyscall-flags = -shared -s -Wl,-soname=linux-gate.so.1 -Wl,--hash-style=sysv
>  
>  SYSCFLAGS_vsyscall-trapa.so	= $(vsyscall-flags)
>  
> -- 
> 2.21.0.593.g511ec345e18-goog
> 

-- 
Yosinori Sato
